In [ ]:
#Importar librerias
import pandas as pd
import numpy as np

In [ ]:
#Traer la base de datos
from google.colab import files
uploated = files.upload()

Saving ventas_sucias_5000.csv to ventas_sucias_5000.csv

In [ ]:
df = pd.read_csv('ventas_sucias_5000.csv')

## **Parte 1 — Exploración de datos (Pandas)**

In [41]:
# Mostrar primeras filas
df.head()

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,NaN,peru,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2,chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9,Colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3,Perú,TRANSFERENCIA,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6,chile,Tarjeta,2024-01-01 04:00:00

In [ ]:
# Mostrar informacion general del data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      5000 non-null   object
 1   producto     5000 non-null   object
 2   precio       4950 non-null   float64
 3   cantidad     4950 non-null   object
 4   pais         5000 non-null   object
 5   metodo_pago  5000 non-null   object
 6   fecha        5000 non-null   object
dtypes: float64(1), object(6)
memory usage: 273.6+ KB

In [ ]:
#Hacer un resumen estadistico
df.describe(include='all')

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
count,5000,5000,4950.000000,4950,5000,5000,5000
unique,6,5,NaN,10,7,4,4825
top,Ana,Mouse,NaN,2,chile,TRANSFERENCIA,2024-01-19 00:00:00
freq,870,1069,NaN,573,733,1276,5
mean,NaN,NaN,5053.823434,NaN,NaN,NaN,NaN
std,NaN,NaN,63379.982009,NaN,NaN,NaN,NaN
min,NaN,NaN,10.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,531.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,1027.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,1519.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,999999.000000,NaN,NaN,NaN,NaN

In [ ]:
#unique para encontrar valores insosistentes
df["pais"].unique()

array(['peru', 'chile', 'Colombia', 'Perú', 'COL', 'Chile', 'col'],
      dtype=object)

In [ ]:
df["metodo_pago"].unique()

array(['Efectivo', 'Tarjeta', 'TRANSFERENCIA', 'transferencia'],
      dtype=object)

In [ ]:
df1 = df.copy()

**¿Cuántas filas y columnas tiene la base de datos?**
 - Tiene 7 columnas y 5000 filas -
**¿Qué tipos de datos identificas?**
 - 6 datos son tipo object y 1 tioo float
**¿Encuentras columnas con problemas o inconsistencias?**
 - Las columnas precio y cantidad tienen valores faltantes

### **Parte 2 — Limpieza de datos (Pandas)**

 • Corregir tipos de datos incorrectos

In [ ]:
df1["cantidad"]= pd.to_numeric(df1["cantidad"], errors="coerce")

- Identificar y manejar valores nulos

In [ ]:
df.isnull().sum()

cliente         0
producto        0
precio         50
cantidad       50
pais            0
metodo_pago     0
fecha           0
dtype: int64

In [ ]:
# rrelnar valores nulos con el promedio
df1["precio"] = df1["precio"].fillna(df["precio"].median())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      5000 non-null   object
 1   producto     5000 non-null   object
 2   precio       5000 non-null   float64
 3   cantidad     4900 non-null   float64
 4   pais         5000 non-null   object
 5   metodo_pago  5000 non-null   object
 6   fecha        5000 non-null   object
dtypes: float64(2), object(5)
memory usage: 273.6+ KB

In [42]:

df1["cantidad"] = df1["cantidad"].fillna(df1["cantidad"].median())
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4980 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      4980 non-null   object
 1   producto     4980 non-null   object
 2   precio       4980 non-null   float64
 3   cantidad     4980 non-null   float64
 4   pais         4980 non-null   object
 5   metodo_pago  4980 non-null   object
 6   fecha        4980 non-null   datetime64[ns]
 7   total        4980 non-null   float64
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 479.2+ KB

- Estandarizar columnas

In [ ]:
# Unificar formatos de letra en miniscula y espaciado
df1["pais"]=df1["pais"].str.lower().str.strip()
# Manejar valores con espacios o vacios
df1["pais"] = df1["pais"].replace("", None)
df1["pais"] = df1["pais"].replace(" ", None)

In [ ]:
#Estandarizar nombres similares para un mismo valor
df1["pais"] = df1["pais"].replace({
    "col" : "colombia",
    "perú" : "peru"
}
)

In [ ]:
df1["metodo_pago"]=df1["metodo_pago"].str.lower().str.strip()
df1["metodo_pago"] = df1["metodo_pago"].replace("", None)
df1["metodo_pago"] = df1["metodo_pago"].replace(" ", None)

• Revisar posibles valores atípicos (outliers)

In [ ]:
df1 = df1[df1["precio"]<100000]

In [ ]:
df1.head()

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,5.0,peru,efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2.0,chile,tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9.0,colombia,efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3.0,peru,transferencia,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6.0,chile,tarjeta,2024-01-01 04:00:00

- Corregir formatos de fecha si es necesario

In [ ]:
df1["fecha"] = pd.to_datetime(df1["fecha"], errors = "coerce", format = "mixed", dayfirst= True)
df1 = df1.dropna(subset=["fecha"])

In [39]:
df1.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 4980 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      4980 non-null   object
 1   producto     4980 non-null   object
 2   precio       4980 non-null   float64
 3   cantidad     4980 non-null   float64
 4   pais         4980 non-null   object
 5   metodo_pago  4980 non-null   object
 6   fecha        4980 non-null   datetime64[ns]
 7   total        4980 non-null   float64
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 479.2+ KB

In [40]:
df1.describe(include = "all")

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha,total
count,4980,4980,4980.000000,4980.000000,4980,4980,4980,4980.000000
unique,6,5,NaN,NaN,3,3,NaN,NaN
top,Ana,Mouse,NaN,NaN,colombia,transferencia,NaN,NaN
freq,865,1063,NaN,NaN,2131,2521,NaN,NaN
mean,NaN,NaN,1017.629719,4.959237,NaN,NaN,2024-04-14 19:42:31.084337408,5048.587952
min,NaN,NaN,10.000000,1.000000,NaN,NaN,2024-01-01 00:00:00,10.000000
25%,NaN,NaN,535.750000,3.000000,NaN,NaN,2024-02-22 09:45:00,1676.000000
50%,NaN,NaN,1027.000000,5.000000,NaN,NaN,2024-04-14 19:30:00,3940.000000
75%,NaN,NaN,1509.000000,7.000000,NaN,NaN,2024-06-05 15:15:00,7551.000000
max,NaN,NaN,1997.000000,9.000000,NaN,NaN,2024-12-04 00:00:00,17955.000000
std,NaN,NaN,568.056778,2.554673,NaN,NaN,NaN,4105.989846

## **Parte 3 — Análisis con Pandas**

In [45]:
df1['total'] = df1['precio'] * df1['cantidad']
print("Total vendido", df1["total"].sum())
print("Promedio", df1["total"].mean())
print("Venta maxima", df1["total"].max())
print("Venta minima", df1["total"].min())
top_productos = df1.groupby("producto")["cantidad"].sum().sort_values(ascending=False)
print(top_productos)

Total vendido 25141968.0
Promedio 5048.587951807229
Venta maxima 17955.0
Venta minima 10.0
producto
Mouse      5300.0
Laptop     4979.0
Monitor    4928.0
Celular    4794.0
Teclado    4696.0
Name: cantidad, dtype: float64

Los 5 productos con mayor valor vendido:


1.   Mause
2.   Laptop
3.   Monitor
4.   Celular
5.   Teclado

El país con más ventas

Colombia (del describe)

## **Parte 4 — NumPy**

In [36]:
totales = df1[['precio','cantidad']].to_numpy() # convertir columnas numericas a array
# Separar columnas utilizando indexación:
precios = totales[:, 0]
cantidades = totales[:, 1]

### **Parte 5 — Análisis con NumPy**

In [35]:
totales = precios * cantidades # CAlculo por vectorizacion
print(totales)
print("total de ventas: ", np.sum(totales))
print("promedio de ventas: ", np.mean(totales))
print("venta minima: ", np.max(totales))
print("ventas mayores a 1000: ", len(totales[totales>1000])) #encontrar valores superiores a 1000 y cuantos hay

[ 6630.   110. 10827. ...  3552. 10928.   406.]
total de ventas:  25141968.0
promedio de ventas:  5048.587951807229
venta minima:  17955.0
ventas mayores a 1000:  4236

¿Qué ventajas observas al usar NumPy? Es mas rapido por que usa menos memoria ram, hace operaciones mas complejas ya que usa matrices para acceder a todos los datos de forma mas facil
¿Qué significa “vectorización”? es la tecnica que usa nampy para hacer operaciones a matrices, disminuyendo el uso de ciclos, ya que es capaz de trabajar sobre blouqes para acceder mas rapido a ellos
¿Qué hace la expresión data[:, 0]? Le dice a la matriz que precios la va a encontrar en la columna de precio y que tome la columna completa

**Parte 6 — Interpretación de resultados**

**Analiza y responde:**
¿Los resultados obtenidos tienen sentido?
  *Si, los datos no tienen valores demasiado elevados, paracen estar bien parametrados y son congruentes en valores matematicos como el promedio por la cantidad de entradas siendo igual al total de ventas, todo gracias a la limpieza, donde se rellenaron los datos faltantes con el promedio *
¿Detectaste valores sospechosos?
  *Si, el valor maximo antes de manejar esos outliers era demasiado alto, y esto podria haber generado polarizacion incorrecta en el promedio*
¿El promedio representa correctamente los datos?
  *Si, habiendo mas de 4000 datos con valores mayores a 1000 y datos con valores grandes como el max de 17000 es coherente pensar que el promedio podria estar rondando los 5000, ademas al manejar los vacios y outliers fue posible un promedio mas cercano y coherente a los datos reales*
¿Qué decisiones tomarías si esta fuera información real de negocio?
  *Le daria peso al mercado que mas se esta moviendo, en este caso en Colombia, mantendria un stock favorable para productos top como mause, tambien facilitaria y evidenciaria de forma diredta a los clientes para informales que pueden haacer pagos por transferencia ya que es el medio de pago que mas se uso, con el total de ventas y  los promedios podria calcular la viabilidad y hacer predicciones futuras de ventas y como se verian afectadas proporcionalmente en posibles expansiones o replicas en otros paises  *